### ISSUE TITLE
Azure toolkit unable to login with any method to azure account - Failed to Cannot login due to error

### ISSUE THREAD

**Issue by gkoperczak001** [microsoft/azure-tools-for-java#5246]
With new macbook (M1 chip) its not possible to use azure toolkit plugin - its failing to login with any available method.
From idea logs we can see "Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.aad.msal4jextensions.persistence.mac.ISecurityLibrary"
![error](https://user-images.githubusercontent.com/38310585/118866785-a4af3e80-b8e2-11eb-897e-9454fd1e5b88.jpg)
[idea.log.zip](https://github.com/microsoft/azure-tools-for-java/files/6510964/idea.log.zip)

**Comment by gkoperczak001** [comment]
It looks its working with 3.51.0-2021.1 with device login

**Comment by andxu** [comment]
@gkoperczak001 thanks for reporting this error, we will investigate it.

**Comment by andxu** [comment]
external  bug: https://github.com/AzureAD/microsoft-authentication-extensions-for-java/issues/31

**Comment by thevangelist** [comment]
Pls Fix

**Comment by andxu** [comment]
hi @thevangelist, I cannot reproduce, could you please try this code in intellij idea?

create a simple java project(maven or gradle) and add this dependency : https://mvnrepository.com/artifact/com.microsoft.azure/msal4j-persistence-extension/1.1.0
```java
package com.example.sample;

import com.microsoft.aad.msal4jextensions.persistence.mac.ISecurityLibrary;

public class App {
    public static void main(String[] args) {
        ISecurityLibrary.library.CFRelease(null);
    }
}

```

**Comment by thevangelist** [comment]
Hey, 

I am not very familiar with Java but I was able to create a minimal maven app and package it. When I use that 1.1.0 dependency and run the freshly-made .jar, I get exception like this:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/microsoft/aad/msal4jextensions/persistence/mac/ISecurityLibrary
	at sample.Sample.main(Sample.java:8)
Caused by: java.lang.ClassNotFoundException: com.microsoft.aad.msal4jextensions.persistence.mac.ISecurityLibrary
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 1 more

```

My pom.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>Azure-Tools-For-Java-Test</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.target>1.8</maven.compiler.target>
        <maven.compiler.source>1.8</maven.compiler.source>
    </properties>

    <build>
        <defaultGoal>package</defaultGoal>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>lib/</classpathPrefix>
                            <mainClass>sample.Sample</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>msal4j-persistence-extension</artifactId>
            <version>1.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-jar-plugin</artifactId>
            <version>3.2.0</version>
            <type>maven-plugin</type>
        </dependency>
    </dependencies>

</project>
```

**Comment by andxu** [comment]
Fixed in https://github.com/microsoft/azure-tools-for-java/pull/6278
